# Label PRs that touch certain files or folders

api:
  - "app/api/**"
  - "utils/**"
frontend:
  - "components/**"
  - "app/**/*.tsx"
  - "app/**/*.ts"
test:
  - "__tests__/**"
documentation:
  - "docs/**"
  - "**/*.md"
