import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { AuthProvider } from "@/components/context/AuthContext";
import NavBar from "@/components/ui/NavBar";
import dynamic from 'next/dynamic';

// Dynamically import StagewiseToolbar with SSR disabled
const StagewiseToolbar = dynamic(
  () => import('@stagewise/toolbar-next').then((mod) => mod.StagewiseToolbar),
  { ssr: false }
);

// Dynamically import ReactPlugin with SSR disabled
const ReactPlugin = dynamic(
  () => import('@stagewise-plugins/react').then((mod) => mod.ReactPlugin),
  { ssr: false }
);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <NavBar />
          <main>{children}</main>
          <StagewiseToolbar 
            config={{
              plugins: [
                ReactPlugin && new ReactPlugin()
              ].filter(Boolean)
            }} 
          />
        </AuthProvider>
      </body>
    </html>
  );
}
